[project]
name = "docs"
version = "1.0.0"
description = "Lasting docs for dev1-sg"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.4",
    "requests>=2.32.4",
    "jinja2>=3.1.6"
]

[project.optional-dependencies]
dev = [
    "ruff>=0.12.7"
]
