name: Cdk Deploy stack

on:
  push:
    branches:
      - main
    paths:
      - src/**
  pull_request:
    paths:
      - src/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  AWS_DEFAULT_REGION: ap-southeast-1
  AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Singapore

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/dev1-sg/ci/aws-cdk:debian
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set shell options
        shell: bash
        run: set -euxo pipefail

      - name: Setup qemu
        uses: docker/setup-qemu-action@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ ENV.AWS_OIDC_ROLE_ARN }}
          role-session-name: aws-oidc-${{ github.repository.name }}-${{ github.run_id }}
          aws-region: ${{ ENV.AWS_DEFAULT_REGION }}

      - name: Install Python dependencies
        working-directory: src/docker-image-assets
        shell: bash
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Cdk deploy
        working-directory: src/docker-image-assets
        shell: bash
        run: |
          source .venv/bin/activate
          cdk bootstrap --qualifier d1sg-ecr
          cdk deploy --all --ci --require-approval never

  dependabot-pr:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/dev1-sg/ci/aws-cdk:debian
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set shell options
        shell: bash
        run: set -euxo pipefail

      - name: Setup qemu
        uses: docker/setup-qemu-action@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Python dependencies
        working-directory: src/docker-image-assets
        shell: bash
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Cdk validate
        working-directory: src/docker-image-assets
        shell: bash
        run: |
          source .venv/bin/activate
          cdk synth

      - name: Auto-merge for Dependabot PR
        run: gh pr merge --auto --rebase ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
